import { GoogleGenAI, Part, Type } from "@google/genai";
import { Activity, LessonPlan, SLO } from '../types';

/**
 * Parses the JSON response from the model into a LessonPlan object.
 * @param jsonText The raw JSON string from the Gemini API.
 * @param gradeLevel The grade level context for the lesson.
 * @param subject The subject for the lesson.
 * @returns A LessonPlan object.
 * @throws An error if parsing fails or the JSON is malformed.
 */
function parseLessonPlanJson(jsonText: string, gradeLevel: string, subject: string): LessonPlan {
    try {
        // The model might sometimes wrap the JSON in markdown backticks.
        const cleanJsonText = jsonText.replace(/^```json\s*|```$/g, '').trim();
        const parsed = JSON.parse(cleanJsonText);

        // Basic validation
        if (!parsed.title || !parsed.objective || !Array.isArray(parsed.activities)) {
            throw new Error("Parsed JSON is missing required fields (title, objective, activities).");
        }

        return {
            ...parsed,
            gradeLevel,
            subject,
        };
    } catch (e) {
        console.error("Error parsing lesson plan JSON:", e);
        console.error("Received text from model:", jsonText);
        if (e instanceof Error) {
            throw new Error(`Failed to parse lesson plan JSON from model: ${e.message}`);
        }
        throw new Error("Failed to parse the lesson plan JSON generated by the model.");
    }
}


export async function generateLessonPlan(
    slo: SLO, 
    unitSlos: SLO[],
    contextFilePart?: Part
): Promise<LessonPlan> {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set.");
  }

  let gradeLevelContext: string;
  const gradeNum = parseInt(slo.grade?.replace('Grade ', '') || '9', 10);

  if (gradeNum <= 10) {
    gradeLevelContext = `${slo.grade} (Foundational)`;
  } else {
    gradeLevelContext = `${slo.grade} (Advanced)`;
  }
  
  const systemInstruction = `You are an expert curriculum developer for ${gradeLevelContext} Physics. Your task is to generate a concise, 40-minute lesson plan as a JSON object.

**Critical Instructions:**
1.  **Strictly Grounded:** Your primary source of information is the attached PDF document. Base the entire lesson plan ONLY on the content found within this document, guided by the provided Student Learning Outcome (SLO). Use the other SLOs from the same unit for context on where this lesson fits.
2.  **Deconstruct Topic & Pace:** Analyze the requested SLO to identify a focused sub-topic suitable for a single 40-minute lesson. The lesson plan must be granular and specific, not covering an entire broad chapter.
3.  **MANDATORY JSON OUTPUT:** The output must ONLY be a valid JSON object matching the provided schema. Do not add any extra text, headers, or conversational markdown. The total duration of all activities must sum to exactly 40 minutes.
4.  **Grade Appropriateness:** All content, activities, and assessments must be appropriate for the specified grade level: ${gradeLevelContext}.
5.  **Activities:** The 'activities' array should contain four distinct objects representing a logical lesson flow: Activating Prior Knowledge, Acquiring New Knowledge, Applying Knowledge, and Assessment.
`;

  const lessonPlanSchema = {
    type: Type.OBJECT,
    properties: {
        title: { 
            type: Type.STRING,
            description: "A concise, specific topic for a 40-minute lesson derived from the main SLO.",
        },
        objective: {
            type: Type.STRING,
            description: "A clear restatement of the user's provided SLO, framed as a student learning objective.",
        },
        materials: {
            type: Type.ARRAY,
            description: "A list of necessary resources, including textbook pages if possible.",
            items: { type: Type.STRING },
        },
        activities: {
            type: Type.ARRAY,
            description: "An array of four activities that structure the lesson.",
            items: {
                type: Type.OBJECT,
                properties: {
                    name: { type: Type.STRING, description: "The name of the activity (e.g., 'Activating Prior Knowledge')." },
                    duration: { type: Type.INTEGER, description: "Duration of the activity in minutes." },
                    description: { type: Type.STRING, description: "A detailed, PDF-grounded description of the activity." },
                },
                required: ['name', 'duration', 'description'],
            },
        },
        assessment: {
            type: Type.STRING,
            description: "A description of the assessment activity, which should be the same as the description of the final activity in the 'activities' array.",
         },
    },
    required: ['title', 'objective', 'materials', 'activities', 'assessment'],
  };

  const contextText = unitSlos
    .filter(s => s.uniqueId !== slo.uniqueId)
    .map(s => `- ${s.SLO_ID}: ${s.SLO_Text}`)
    .join('\n');

  const userPrompt = `Generate a lesson plan for the following SLO:
**${slo.SLO_ID}: ${slo.SLO_Text}**

For context, here are other SLOs from the same unit:
${contextText || 'None'}

Use the attached PDF as the primary reference for content, examples, and activities.
`;

  try {
    const parts: Part[] = [{ text: userPrompt }];
    if (contextFilePart) {
        parts.unshift(contextFilePart); // Put PDF first for better context
    }

    const response = await ai.models.generateContent({
      model: 'gemini-flash-lite-latest',
      contents: { parts },
      config: {
        systemInstruction: systemInstruction,
        temperature: 0.2,
        responseMimeType: "application/json",
        responseSchema: lessonPlanSchema,
      },
    });

    const lessonPlan = parseLessonPlanJson(response.text, gradeLevelContext, 'Physics');
    
    return lessonPlan;
  } catch (error) {
    console.error("Error generating lesson plan:", error);
    if (error instanceof Error) {
        if (error.message.includes('429')) {
             throw new Error("API rate limit exceeded. Please try again later.");
        }
        if (error.message.includes('API key not valid')) {
            throw new Error("Invalid API Key. Please check your configuration.");
        }
        if (error.message.includes('Failed to parse')) {
            throw error;
        }
    }
    throw new Error("Failed to generate lesson plan. The model may have returned an unexpected response.");
  }
}