/**
 * Helper to robustly parse JSON from a potentially markdown-wrapped string.
 * @param text - The text to parse
 * @returns The parsed JSON object
 */
export function cleanAndParseJson(text: string): any {
    let cleanText = text.replace(/```json\s*/g, '').replace(/```\s*$/g, '');
    const firstBrace = cleanText.indexOf('{');
    const lastBrace = cleanText.lastIndexOf('}');
    
    if (firstBrace !== -1 && lastBrace !== -1) {
        cleanText = cleanText.substring(firstBrace, lastBrace + 1);
    }
    
    return JSON.parse(cleanText);
}

/**
 * Parses the JSON response from the model into a LessonPlan object.
 * @param jsonText - The raw JSON text from the model
 * @param gradeLevel - The grade level to assign
 * @param subject - The subject to assign
 * @returns The parsed lesson plan
 * @throws Error if required fields are missing or JSON is invalid
 */
export function parseLessonPlanJson(jsonText: string, gradeLevel: string, subject: string): any {
    try {
        const parsed = cleanAndParseJson(jsonText);

        if (!parsed.title || !parsed.objective || !Array.isArray(parsed.activities) || !parsed.homework) {
            throw new Error("Parsed JSON is missing required fields (title, objective, activities, homework).");
        }

        return {
            ...parsed,
            gradeLevel,
            subject,
        };
    } catch (e) {
        console.error("Error parsing lesson plan JSON:", e);
        if (e instanceof Error) {
            throw new Error(`Failed to parse lesson plan JSON from model: ${e.message}`);
        }
        throw new Error("Failed to parse the lesson plan JSON generated by the model.");
    }
}
