export const REMOTE_PDF_BASE_URL = 'https://raw.githubusercontent.com/abdulahadattar/STBB-BOOKS/main/';

export const REMOTE_PDF_FILE_NAMES = [
    "Grade 9/Physics Grade 9 Unit 0 INDEX_.pdf",
    "Grade 9/Physics Grade 9 Unit 1 PHYSICAL QUANTITIES AND MEASUREMENT_.pdf",
    "Grade 9/Physics Grade 9 Unit 2 KINEMATICS_.pdf",
    "Grade 9/Physics Grade 9 Unit 3 DYNAMICS_.pdf",
    "Grade 9/Physics Grade 9 Unit 4 TURNING EFFECT OF FORCES_.pdf",
    "Grade 9/Physics Grade 9 Unit 5 FORCES AND MATTER_.pdf",
    "Grade 9/Physics Grade 9 Unit 6 GRAVITATION_.pdf",
    "Grade 9/Physics Grade 9 Unit 7 PROPERTIES OF MATTER_.pdf",
    "Grade 9/Physics Grade 9 Unit 8 ENERGY SOURCES AND TRANSFER OF ENERGY_.pdf",
    "Grade 9/Physics Grade 9 Unit 9 THERMAL PROPERTIES OF MATTER_.pdf",
    "Grade 10/Physics Grade 10 Unit 0 INDEX_.pdf",
    "Grade 10/Physics Grade 10 Unit 10 General Waves Properties_.pdf",
    "Grade 10/Physics Grade 10 Unit 11 Sound_.pdf",
    "Grade 10/Physics Grade 10 Unit 12 Electromagnetic Spectrum_.pdf",
    "Grade 10/Physics Grade 10 Unit 13 Geometrical Optics_.pdf",
    "Grade 10/Physics Grade 10 Unit 14 Electrostatics_.pdf",
    "Grade 10/Physics Grade 10 Unit 15 Current Electricity_.pdf",
    "Grade 10/Physics Grade 10 Unit 16 Electromagnetism_.pdf",
    "Grade 10/Physics Grade 10 Unit 17 Introductory Electronics_.pdf",
    "Grade 10/Physics Grade 10 Unit 18 Information and Communication Technology ICT_.pdf",
    "Grade 10/Physics Grade 10 Unit 19 Atomic Structure_.pdf",
    "Grade 10/Physics Grade 10 Unit 20 Nuclear Structure_.pdf",
    "Grade 11/Physics Grade 11 Unit 00 INDEX_.pdf",
    "Grade 11/Physics Grade 11 Unit 01 Measurements_.pdf",
    "Grade 11/Physics Grade 11 Unit 02 Kinematics_.pdf",
    "Grade 11/Physics Grade 11 Unit 03 Dynamics_.pdf",
    "Grade 11/Physics Grade 11 Unit 04 Rotational and Circular Motion_.pdf",
    "Grade 11/Physics Grade 11 Unit 05 Work, Energy and Power_.pdf",
    "Grade 11/Physics Grade 11 Unit 06 Fluid Statics_.pdf",
    "Grade 11/Physics Grade 11 Unit 07 Fluid Dynamics_.pdf",
    "Grade 11/Physics Grade 11 Unit 08 Electric Fields part1_.pdf",
    "Grade 11/Physics Grade 11 Unit 08 Electric Fields part2_.pdf",
    "Grade 11/Physics Grade 11 Unit 09 Capacitors_.pdf",
    "Grade 11/Physics Grade 11 Unit 10 D.C Circuits_.pdf",
    "Grade 11/Physics Grade 11 Unit 11 Oscillations_.pdf",
    "Grade 11/Physics Grade 11 Unit 12 Acoustics_.pdf",
    "Grade 11/Physics Grade 11 Unit 13 Physical Optics_.pdf",
    "Grade 11/Physics Grade 11 Unit 14 Communication_.pdf",
    "Grade 12/Physics Grade 12 Unit 00 INDEX_.pdf",
    "Grade 12/Physics Grade 12 Unit 15 Molecular Theory of Gases_.pdf",
    "Grade 12/Physics Grade 12 Unit 16 First Law of Thermodynamics_.pdf",
    "Grade 12/Physics Grade 12 Unit 17 Second Law of Thermodynamics_.pdf",
    "Grade 12/Physics Grade 12 Unit 18 Magnetic Fields_.pdf",
    "Grade 12/Physics Grade 12 Unit 19 Electromagnetic Induction_.pdf",
    "Grade 12/Physics Grade 12 Unit 20 Alternating Current_.pdf",
    "Grade 12/Physics Grade 12 Unit 21 Physics of Solids_.pdf",
    "Grade 12/Physics Grade 12 Unit 22 Solid State of Electronics part1_.pdf",
    "Grade 12/Physics Grade 12 Unit 22 Solid State of Electronics part2_.pdf",
    "Grade 12/Physics Grade 12 Unit 23 Digital Electronics_.pdf",
    "Grade 12/Physics Grade 12 Unit 24 Relativity_.pdf",
    "Grade 12/Physics Grade 12 Unit 25 Quantum Physics_.pdf",
    "Grade 12/Physics Grade 12 Unit 26 Atomic Physics_.pdf",
    "Grade 12/Physics Grade 12 Unit 27 Nuclear Physics_.pdf",
    "Grade 12/Physics Grade 12 Unit 28 Particles Physics_.pdf",
] as const;
